HW for 7/28/22
awesomeprogrammer1/python pull request #11
Opened 2022-07-27 22:09 UTC by awesomeprogrammer1

# what

HW to be Completed by 7/28/22

2022-07-28 00:24 UTC, sryabkov requested changes
Look at inline comments

Before you submit, you need to run `python3 -m pytest` in the `code_school` directory and make sure you get no errors

2022-07-28 00:24 UTC, sryabkov commented on code_school/functions.py
> +    return result
Not quite... Try again.

Hint: look at `functions_test.py`

2022-07-28 00:24 UTC, sryabkov commented on code_school/functions.py
> +def print_perimeter_area_rectangle_dict(dict):
You need to implement this function

2022-07-28 01:11 UTC, awesomeprogrammer1 commented on code_school/functions.py
> +    area = width * height; perimeter = (width+height)*2 ; result = f'P = {perimeter}, Area = {area}' ; return result
Fixed

2022-07-28 01:27 UTC, awesomeprogrammer1 commented on code_school/functions.py
> +    return result
Fixed assignment

2022-07-28 01:35 UTC, sryabkov requested changes
See inline comments... 

and RUN THE TESTS before submitting!

2022-07-28 01:35 UTC, sryabkov commented on code_school/functions.py
> +    return result
Should be one line, not two...

2022-07-28 01:35 UTC, sryabkov commented on code_school/functions.py
> +    return result
Do the tests pass?

2022-07-28 01:39 UTC, awesomeprogrammer1 commented on code_school/functions.py
> +    return result
Test number one has passed, test number two has failed

2022-07-28 02:06 UTC, sryabkov commented on code_school/functions.py
> +    return result
I don't believe you: both tests fail on my machine

2022-07-28 22:27 UTC, awesomeprogrammer1 commented on code_school/functions.py
> +    return result
Fixed

2022-07-28 23:10 UTC, awesomeprogrammer1 commented on code_school/functions.py
> +    return result
Both tests passed

2022-07-28 23:10 UTC, awesomeprogrammer1 commented on code_school/functions.py
> +def print_perimeter_area_rectangle_dict(dict):
Implemented

2022-07-29 01:33 UTC, sryabkov commented on code_school/functions.py
> +    dict["Area"] = width * height
```suggestion
    dict = {}
    dict["Area"] = width * height
```

2022-07-29 01:34 UTC, sryabkov reviewed
Looks OK, see a couple of minor comments

2022-07-29 09:50 UTC, sryabkov commented on code_school/functions.py
> +    ""
```suggestion
```

What is this?

2022-07-29 09:51 UTC, sryabkov approved these changes

2022-07-29 21:25 UTC, awesomeprogrammer1 commented on code_school/functions.py
> +    ""
Fixed

2022-07-29 21:26 UTC, awesomeprogrammer1 commented on code_school/functions.py
> +    dict["Area"] = width * height
Fixed

2022-07-29 21:27 UTC, merged