Homework for 2022-07-11
awesomeprogrammer1/python pull request #7
Opened 2022-07-10 13:52 UTC by awesomeprogrammer1

# what

Homework for 2022-07-11

# why

Practice what we studied on 2022-07-09

2022-07-10 17:59 UTC, awesomeprogrammer1 commented on code_school/dictionary-hw.py
> +        print("I do not have an opinion on that thing. Check for a typo and make sure that all letters are lowercase.")
I fixed that

2022-07-10 17:59 UTC, awesomeprogrammer1 commented on code_school/dictionary.py
> +)  # Returns the value of the specified key. If the key does not exist then insert the key with the specified value
Yes, done

2022-07-10 18:04 UTC, sryabkov requested changes

2022-07-10 18:04 UTC, sryabkov commented on code_school/dictionary-hw.py
> +        print("Correct! You Know Me Very Well")
Why is `You Know Me Very Well` capitalized like this and the other messages are not? 
Can you please pick one style for all messages?
Hint: do **not** use Title Case

2022-07-10 18:04 UTC, sryabkov commented on code_school/dictionary.py
> +# returns the value and adds the key to the dictionary if it exists. If 9it doesnt, it returns "None" and adds
<img width="713" alt="image" src="https://user-images.githubusercontent.com/178154/178156678-7d496f99-3064-46fe-a4d8-66a00f026e1c.png">

What is `9it` and did you run out of words in the end?

2022-07-10 18:09 UTC, awesomeprogrammer1 commented on code_school/dictionary-hw.py
> +        print("Correct! You Know Me Very Well")
I got it, accidentally capitalized, fixed now

2022-07-10 18:21 UTC, sryabkov requested changes

2022-07-10 18:21 UTC, sryabkov commented on code_school/dictionary-hw.py
> +    guess = guess.lower()
Can you combine these two lines into one?

2022-07-10 18:21 UTC, sryabkov commented on code_school/dictionary.py
> +# returns the value and adds the key to the dictionary if it exists. If it doesnt, it returns "None" and adds it to the list
What is "it" in "add it to the list?" 

Hint: You had a better explanation in the table. Try copying/pasting from the table

2022-07-10 18:21 UTC, sryabkov commented on code_school/dictionary.py
> +# returns the value if the key exists. If it doesn't there is an error
```suggestion
# returns the value if the key exists. If it doesn't, there is an error
```

2022-07-10 18:21 UTC, sryabkov commented on code_school/dictionary.py
> +# returns the value if the key exists. If it doesn't it returns "None"
```suggestion
# returns the value if the key exists. If it doesn't, the method returns "None"
```

2022-07-10 18:21 UTC, sryabkov commented on code_school/dictionary.py
> +# the for statement inserts elements between one and one hundred, which are the keys. Then, the keys are multiplied by two to get the values
"get the values"? Or something else?

Hint: we talked about it

2022-07-10 18:21 UTC, sryabkov commented on code_school/dictionary.py
> +#  all the elements of the list are taken into the dictionary, which are the keys. The keys are then divided by two, thus giving us the values
"taken into the dictionary"? What is the correct terminology and a shorter way to say this?

2022-07-10 18:21 UTC, sryabkov commented on code_school/dictionary.py
> +# all the elements of the list that are even are put into the dictionary as keys and then multiplied by two for the values
That comment is incorrect

2022-07-10 18:21 UTC, sryabkov commented on code_school/dictionary.py
> +####################################################
What are we doing in the last portion of the program? Can you please add a comment explaining it?

2022-07-10 18:28 UTC, awesomeprogrammer1 commented on code_school/dictionary.py
> +# returns the value and adds the key to the dictionary if it exists. If it doesnt, it returns "None" and adds it to the list
Fixed

2022-07-10 18:47 UTC, awesomeprogrammer1 commented on code_school/dictionary.py
> +####################################################
This was incomplete during the lesson, so I didn't want to do it because I wasn't able to get it.

2022-07-10 18:53 UTC, awesomeprogrammer1 commented on code_school/dictionary.py
> +#  all the elements of the list are taken into the dictionary, which are the keys. The keys are then divided by two, thus giving us the values
fixed

2022-07-10 18:55 UTC, awesomeprogrammer1 commented on code_school/dictionary.py
> +# all the elements of the list that are even are put into the dictionary as keys and then multiplied by two for the values
adjusted.

2022-07-10 19:01 UTC, sryabkov requested changes

2022-07-10 19:01 UTC, sryabkov commented on code_school/dictionary.py
> +####################################################
Not true: we finished this piece of code. 

Figure out what's doing if you forgot and then ask for help if you still don't get it

2022-07-10 19:18 UTC, sryabkov requested changes

2022-07-10 19:18 UTC, sryabkov commented on code_school/dictionary.py
> +# and display it
This is not accurate

2022-07-10 19:18 UTC, sryabkov commented on code_school/dictionary.py
> +# We get the value of the element by dividing the key by two.
What about the key? What's the key?

2022-07-10 19:22 UTC, awesomeprogrammer1 commented on code_school/dictionary.py
> +# We get the value of the element by dividing the key by two.
Made it more specific, should be better now

2022-07-10 19:33 UTC, sryabkov commented on code_school/dictionary.py
> +# We get the value of the element by dividing the key by two.
Looks good

2022-07-10 19:35 UTC, sryabkov commented on code_school/dictionary.py
> +# add/remove an element
```suggestion
# add/remove an element to/from the dictionary
```

2022-07-10 19:40 UTC, awesomeprogrammer1 commented on code_school/dictionary.py
> +####################################################
Resolved this

2022-07-10 19:40 UTC, awesomeprogrammer1 commented on code_school/dictionary.py
> +#  all the elements of the list are put into the dictionary. The keys are then divided by two, thus giving us the values
Fixed

2022-07-10 19:40 UTC, awesomeprogrammer1 commented on code_school/dictionary.py
> +# in order to obtain the value of the element
Fixed

2022-07-10 19:41 UTC, awesomeprogrammer1 commented on code_school/dictionary.py
> +# and display it
I have edited this to make it make more sense.

2022-07-10 19:50 UTC, sryabkov commented on code_school/dictionary-hw.py
> +
```suggestion
```

2022-07-10 19:50 UTC, sryabkov commented on code_school/dictionary-hw.py
> +print("Try again next time!")
```suggestion

print("Try again next time!")
```

2022-07-10 19:51 UTC, sryabkov commented on code_school/dictionary.py
> +# in order to obtain the value of the element
> ...Then, all the keys that are even are multiplied by two
> # in order to obtain the value of the element

I like the first sentence, but the second one needs correction

2022-07-10 19:52 UTC, sryabkov commented on code_school/dictionary.py
> +# we create an new empty dictionary
```suggestion
# we create a new empty dictionary
```

2022-07-11 10:38 UTC, sryabkov requested changes

2022-07-11 10:38 UTC, sryabkov commented on code_school/dictionary.py
> +# we fill the dictionary with the letters that were in the string
Please finish this comment

2022-07-11 11:26 UTC, sryabkov approved these changes
LGTM

2022-07-11 11:27 UTC, merged